// Icon mapping utility for dynamic icon loading
import {
  LayoutDashboard,
  User,
  ClipboardList,
  Cog,
  Shield,
  Users,
  Key,
  Settings,
  FileText,
  BarChart3,
  Folder,
  Home,
  Bell,
  Calendar,
  Mail,
  MessageSquare,
  Search,
  Tag,
  Archive,
  Database,
  Package,
  ShoppingCart,
  DollarSign,
  TrendingUp,
  Activity,
  Heart,
  Star,
  Award,
  Target,
  Flag,
  Bookmark,
  CheckSquare,
  AlertCircle,
  Info,
  HelpCircle,
  Map,
  MapPin,
  Navigation,
  Compass,
  Camera,
  Image,
  Film,
  Music,
  Headphones,
  Phone,
  Smartphone,
  Tablet,
  Monitor,
  Printer,
  Wifi,
  Bluetooth,
  Battery,
  Zap,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wind,
  Thermometer,
  Droplet,
  Coffee,
  Book,
  BookOpen,
  Newspaper,
  FileSpreadsheet,
  FileImage,
  FilePlus,
  Download,
  Upload,
  Share2,
  Link,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Edit,
  Trash2,
  Plus,
  Minus,
  X,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  // Utility & LGU Icons
  Warehouse,
  ClipboardCheck,
  Calculator,
  PieChart,
  Layers,
  Grid,
  List,
  Table2,
  Filter,
  SortAsc,
  SortDesc,
  RefreshCw,
  RotateCcw,
  Save,
  Copy,
  Scissors,
  Paperclip,
  Send,
  Power,
  Volume2,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Clock,
  Timer,
  Hourglass,
  PlayCircle,
  PauseCircle,
  StopCircle,
  SkipForward,
  SkipBack,
  Factory,
  Truck,
  Scale,
  Milestone,
  Boxes,
  Container,
  ListChecks,
  ClipboardType,
  Receipt,
  Banknote,
  Coins,
  Wallet,
  CreditCard,
  BadgeCheck,
  BadgeAlert,
  BadgeInfo,
  Gauge,
  Flame,
  Snowflake,
  LucideIcon,
  // LGU-IMS Icons
  Landmark,
  PlusCircle,
  Globe,
  ShoppingBag,
  ArrowRightLeft,
  FileCheck,
  FileOutput,
  FileBarChart,
  Building2,
  UserCheck,
  Briefcase,
  CalendarOff,
  ShieldAlert,
  GraduationCap,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  // Dashboard & Navigation
  dashboard: LayoutDashboard,
  home: Home,
  menu: ClipboardList,
  folder: Folder,

  // User & Profile
  profile: User,
  users: Users,

  // RBAC & Security
  role: Shield,
  activation: Key,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,

  // Management & Settings
  module: Cog,
  settings: Settings,
  cog: Cog,

  // Documents & Files
  assignment: ClipboardList,
  file: FileText,
  document: FileText,
  spreadsheet: FileSpreadsheet,
  image: FileImage,
  fileplus: FilePlus,
  book: Book,
  bookopen: BookOpen,
  newspaper: Newspaper,

  // Analytics & Reports
  chart: BarChart3,
  analytics: BarChart3,
  trending: TrendingUp,
  activity: Activity,

  // Communication
  mail: Mail,
  message: MessageSquare,
  bell: Bell,
  phone: Phone,

  // Calendar & Schedule
  calendar: Calendar,

  // Search & Navigation
  search: Search,
  compass: Compass,
  map: Map,
  mappin: MapPin,
  navigation: Navigation,

  // Tags & Labels
  tag: Tag,
  bookmark: Bookmark,
  flag: Flag,

  // Storage & Archive
  archive: Archive,
  database: Database,
  package: Package,

  // Commerce
  cart: ShoppingCart,
  dollar: DollarSign,

  // Status & Indicators
  heart: Heart,
  star: Star,
  award: Award,
  target: Target,
  check: Check,
  checksquare: CheckSquare,
  alert: AlertCircle,
  info: Info,
  help: HelpCircle,

  // Media
  camera: Camera,
  photo: Image,
  film: Film,
  music: Music,
  headphones: Headphones,

  // Devices
  smartphone: Smartphone,
  tablet: Tablet,
  monitor: Monitor,
  printer: Printer,

  // Connectivity
  wifi: Wifi,
  bluetooth: Bluetooth,

  // Power & Energy
  battery: Battery,
  zap: Zap,

  // Weather & Environment
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  cloudrain: CloudRain,
  wind: Wind,
  thermometer: Thermometer,
  droplet: Droplet,

  // Food & Beverage
  coffee: Coffee,

  // Actions
  download: Download,
  upload: Upload,
  share: Share2,
  link: Link,
  eye: Eye,
  eyeoff: EyeOff,
  edit: Edit,
  trash: Trash2,
  plus: Plus,
  minus: Minus,
  x: X,

  // Arrows & Directions
  left: ChevronLeft,
  right: ChevronRight,
  up: ChevronUp,
  down: ChevronDown,

  // General Utility
  warehouse: Warehouse,
  storage: Warehouse,
  truck: Truck,
  transport: Truck,
  delivery: Truck,
  scale: Scale,
  weight: Scale,
  weigh: Scale,
  factory: Factory,
  plant: Factory,
  facility: Factory,
  milestone: Milestone,
  marker: Milestone,
  gauge: Gauge,
  meter: Gauge,
  measure: Gauge,
  flame: Flame,
  heat: Flame,
  fire: Flame,
  snowflake: Snowflake,
  cold: Snowflake,
  freeze: Snowflake,

  // Inventory & Organization
  boxes: Boxes,
  container: Container,
  listchecks: ListChecks,
  checklist: ListChecks,
  tasks: ListChecks,
  clipboardcheck: ClipboardCheck,
  inspect: ClipboardCheck,
  inspection: ClipboardCheck,
  clipboardtype: ClipboardType,
  form: ClipboardType,
  list: List,
  items: List,
  table: Table2,
  grid: Grid,
  layout: Grid,
  layers: Layers,
  stack: Layers,

  // Financial
  receipt: Receipt,
  invoice: Receipt,
  banknote: Banknote,
  money: Banknote,
  coins: Coins,
  wallet: Wallet,
  creditcard: CreditCard,
  card: CreditCard,
  payment: CreditCard,

  // Data & Analysis
  calculator: Calculator,
  calculate: Calculator,
  piechart: PieChart,
  pie: PieChart,
  filter: Filter,
  sortasc: SortAsc,
  ascending: SortAsc,
  sortdesc: SortDesc,
  descending: SortDesc,

  // Status Badges
  badgecheck: BadgeCheck,
  verified: BadgeCheck,
  badgealert: BadgeAlert,
  warning: BadgeAlert,
  badgeinfo: BadgeInfo,

  // Actions & Controls
  refreshcw: RefreshCw,
  refresh: RefreshCw,
  reload: RefreshCw,
  rotateccw: RotateCcw,
  undo: RotateCcw,
  save: Save,
  copy: Copy,
  duplicate: Copy,
  scissors: Scissors,
  cut: Scissors,
  paperclip: Paperclip,
  attach: Paperclip,
  attachment: Paperclip,
  send: Send,
  submit: Send,
  power: Power,
  onoff: Power,
  volume: Volume2,
  sound: Volume2,
  audio: Volume2,

  // Status Indicators
  alerttriangle: AlertTriangle,
  caution: AlertTriangle,
  checkcircle: CheckCircle,
  success: CheckCircle,
  complete: CheckCircle,
  xcircle: XCircle,
  error: XCircle,
  failed: XCircle,

  // Time & Schedule
  clock: Clock,
  time: Clock,
  timer: Timer,
  countdown: Timer,
  hourglass: Hourglass,
  waiting: Hourglass,
  pending: Hourglass,

  // Media Controls
  playcircle: PlayCircle,
  play: PlayCircle,
  start: PlayCircle,
  pausecircle: PauseCircle,
  pause: PauseCircle,
  stopcircle: StopCircle,
  stop: StopCircle,
  skipforward: SkipForward,
  next: SkipForward,
  skipback: SkipBack,
  previous: SkipBack,
  back: SkipBack,

  // LGU-IMS Module Icons
  landmark: Landmark,
  pluscircle: PlusCircle,
  globe: Globe,
  shoppingbag: ShoppingBag,
  arrowrightleft: ArrowRightLeft,
  filecheck: FileCheck,
  fileoutput: FileOutput,
  filebarchart: FileBarChart,
  building2: Building2,
  usercheck: UserCheck,
  briefcase: Briefcase,
  calendaroff: CalendarOff,
  shieldalert: ShieldAlert,
  graduationcap: GraduationCap,
};

// Icon display names for better UI
const iconDisplayNames: Record<string, string> = {
  dashboard: "Dashboard",
  home: "Home",
  menu: "Menu",
  folder: "Folder",
  profile: "Profile",
  users: "Users",
  role: "Role",
  activation: "Activation",
  lock: "Lock",
  unlock: "Unlock",
  shield: "Shield",
  module: "Module",
  settings: "Settings",
  cog: "Cog",
  assignment: "Assignment",
  file: "File",
  document: "Document",
  spreadsheet: "Spreadsheet",
  image: "Image",
  fileplus: "File Plus",
  book: "Book",
  bookopen: "Book Open",
  newspaper: "Newspaper",
  chart: "Chart",
  analytics: "Analytics",
  trending: "Trending",
  activity: "Activity",
  mail: "Mail",
  message: "Message",
  bell: "Notification",
  phone: "Phone",
  calendar: "Calendar",
  search: "Search",
  compass: "Compass",
  map: "Map",
  mappin: "Map Pin",
  navigation: "Navigation",
  tag: "Tag",
  bookmark: "Bookmark",
  flag: "Flag",
  archive: "Archive",
  database: "Database",
  package: "Package",
  cart: "Shopping Cart",
  dollar: "Dollar",
  heart: "Heart",
  star: "Star",
  award: "Award",
  target: "Target",
  check: "Check",
  checksquare: "Check Square",
  alert: "Alert",
  info: "Info",
  help: "Help",
  camera: "Camera",
  photo: "Photo",
  film: "Film",
  music: "Music",
  headphones: "Headphones",
  smartphone: "Smartphone",
  tablet: "Tablet",
  monitor: "Monitor",
  printer: "Printer",
  wifi: "WiFi",
  bluetooth: "Bluetooth",
  battery: "Battery",
  zap: "Zap",
  sun: "Sun",
  moon: "Moon",
  cloud: "Cloud",
  cloudrain: "Cloud Rain",
  wind: "Wind",
  thermometer: "Thermometer",
  droplet: "Droplet",
  coffee: "Coffee",
  download: "Download",
  upload: "Upload",
  share: "Share",
  link: "Link",
  eye: "Eye",
  eyeoff: "Eye Off",
  edit: "Edit",
  trash: "Trash",
  plus: "Plus",
  minus: "Minus",
  x: "Close",
  left: "Left",
  right: "Right",
  up: "Up",
  down: "Down",

  // General Utility
  warehouse: "Warehouse",
  storage: "Storage",
  truck: "Truck",
  transport: "Transport",
  delivery: "Delivery",
  scale: "Scale",
  weight: "Weight",
  weigh: "Weigh",
  factory: "Factory",
  plant: "Plant",
  facility: "Facility",
  milestone: "Milestone",
  marker: "Marker",
  gauge: "Gauge",
  meter: "Meter",
  measure: "Measure",
  flame: "Flame",
  heat: "Heat",
  fire: "Fire",
  snowflake: "Snowflake",
  cold: "Cold",
  freeze: "Freeze",

  // Inventory & Organization
  boxes: "Boxes",
  container: "Container",
  listchecks: "List Checks",
  checklist: "Checklist",
  tasks: "Tasks",
  clipboardcheck: "Clipboard Check",
  inspect: "Inspect",
  inspection: "Inspection",
  clipboardtype: "Clipboard Type",
  form: "Form",
  list: "List",
  items: "Items",
  table: "Table",
  grid: "Grid",
  layout: "Layout",
  layers: "Layers",
  stack: "Stack",

  // Financial
  receipt: "Receipt",
  invoice: "Invoice",
  banknote: "Banknote",
  money: "Money",
  coins: "Coins",
  wallet: "Wallet",
  creditcard: "Credit Card",
  card: "Card",
  payment: "Payment",

  // Data & Analysis
  calculator: "Calculator",
  calculate: "Calculate",
  piechart: "Pie Chart",
  pie: "Pie",
  filter: "Filter",
  sortasc: "Sort Ascending",
  ascending: "Ascending",
  sortdesc: "Sort Descending",
  descending: "Descending",

  // Status Badges
  badgecheck: "Badge Check",
  verified: "Verified",
  badgealert: "Badge Alert",
  warning: "Warning",
  badgeinfo: "Badge Info",

  // Actions & Controls
  refreshcw: "Refresh",
  refresh: "Refresh",
  reload: "Reload",
  rotateccw: "Rotate CCW",
  undo: "Undo",
  save: "Save",
  copy: "Copy",
  duplicate: "Duplicate",
  scissors: "Scissors",
  cut: "Cut",
  paperclip: "Paperclip",
  attach: "Attach",
  attachment: "Attachment",
  send: "Send",
  submit: "Submit",
  power: "Power",
  onoff: "On/Off",
  volume: "Volume",
  sound: "Sound",
  audio: "Audio",

  // Status Indicators
  alerttriangle: "Alert Triangle",
  caution: "Caution",
  checkcircle: "Check Circle",
  success: "Success",
  complete: "Complete",
  xcircle: "X Circle",
  error: "Error",
  failed: "Failed",

  // Time & Schedule
  clock: "Clock",
  time: "Time",
  timer: "Timer",
  countdown: "Countdown",
  hourglass: "Hourglass",
  waiting: "Waiting",
  pending: "Pending",

  // Media Controls
  playcircle: "Play Circle",
  play: "Play",
  start: "Start",
  pausecircle: "Pause Circle",
  pause: "Pause",
  stopcircle: "Stop Circle",
  stop: "Stop",
  skipforward: "Skip Forward",
  next: "Next",
  skipback: "Skip Back",
  previous: "Previous",
  back: "Back",

  // LGU-IMS Module Icons
  landmark: "Landmark",
  pluscircle: "Plus Circle",
  globe: "Globe",
  shoppingbag: "Shopping Bag",
  arrowrightleft: "Arrow Right Left",
  filecheck: "File Check",
  fileoutput: "File Output",
  filebarchart: "File Bar Chart",
  building2: "Building",
  usercheck: "User Check",
  briefcase: "Briefcase",
  calendaroff: "Calendar Off",
  shieldalert: "Shield Alert",
  graduationcap: "Graduation Cap",
};

export const getIconByName = (iconName: string | null): LucideIcon => {
  if (!iconName) return Cog; // Default icon
  return iconMap[iconName.toLowerCase()] || Cog;
};

export const getIconDisplayName = (iconName: string): string => {
  return (
    iconDisplayNames[iconName.toLowerCase()] ||
    iconName.charAt(0).toUpperCase() + iconName.slice(1)
  );
};

export const availableIcons = Object.keys(iconMap).sort();
